// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason! I am Sai Pc!");

function greetMore(name) {
  return "Hello " + name;
}

console.log("Hello stephan");

exports.greetMore = greetMore;
/*  Not a pure module */
